name: ci

on:
  push:
    branches:
      - 'main'
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login in into Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Reverse proxy
        uses: docker/build-push-action@v3
        with:
          context: https://github.com/innocent-george-mithu-nyamusa/microservices.git#master:udagram-reverseproxy
          push: true
          tags: innocentmithu/reverseproxy:latest
      -
        name: Build and push Frontend
        uses: docker/build-push-action@v3
        with:
          context: https://github.com/innocent-george-mithu-nyamusa/microservices.git#master:udagram-frontend
          push: true
          tags: innocentmithu/udagran-frontend:latest
      -
        name: Build and push Api feed 
        uses: docker/build-push-action@v3
        with:
          context: https://github.com/innocent-george-mithu-nyamusa/microservices.git#master:udagram-api-feed
          push: true
          tags: innocentmithu/udagram-api-feed:latest
      -
        name: Build and push api user
        uses: docker/build-push-action@v3
        with:
          context: https://github.com/innocent-george-mithu-nyamusa/microservices.git#master:udagram-api-user
          push: true
          tags: innocentmithu/udagram-api-user:latest
      
